# -*- mode: ruby -*-
# vim: set ft=ruby :

hosts = {
    :ansible => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :ip_addr => '192.168.1.10',
        :port => '8080'
    },
    :srv1 => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :ip_addr => '192.168.1.21',
        :port => '8081'
    },
    :srv2 => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :ip_addr => '192.168.1.22',
        :port => '8082'
    }
}

Vagrant.configure("2") do |config|

    hosts.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.network "forwarded_port", guest: 80, host: boxconfig[:port]

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = "che-les09-" + "%s" % boxname
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                systemctl restart sshd
                #yum install -y epel-release
                #yum install -y nginx
                #systemctl start nginx
            SHELL

        end
    end
end
