# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.define "web1" do |web|
        web.vm.box = "centos/7"
        web.vm.hostname = "web-srv1"

        config.vm.provider "virtualbox" do |web|
            web.name = "web-server1"
            web.cpus = 1
            web.memory = "1024"
        end

        web.vm.provision "shell", path: "script.sh"

    end

    config.vm.define "web2" do |web|
        web.vm.box = "centos/7"
        web.vm.hostname = "web-srv2"

        config.vm.provider "virtualbox" do |web|
            web.name = "web-server2"
            web.cpus = 2
            web.memory = "2048"
        end

        web.vm.provision "shell", path: "script.sh"

    end
end
