# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant_data"

    config.vm.define "centos7" do |srv|
        srv.vm.hostname = "centos7"

        config.vm.provider "virtualbox" do |srv|
            srv.name = "centos7"
            srv.cpus = 2
            srv.memory = "1024"
        end

        srv.vm.provision "shell", path: "script.sh"
    end
en 
