# -*- mode: ruby -*-
# vim: set ft=ruby :

hosts = {
    :"web" => {
        :box_name => "ubuntu/bionic64",
        :cpu => '2',
        :ram => "2048",
        :ip_addr => '192.168.50.12',
        :port1 => '8085',
        :port2 => '8084'
    },
    :"mon" => {
        :box_name => "ubuntu/bionic64",
        :cpu => '2',
        :ram => "2048",
        :ip_addr => '192.168.50.11',
        :port1 => '8083',
        :port2 => '8082'
    },
    :"ansible" => {
        :box_name => "centos/7",
        :cpu => '2',
        :ram => "2048",
        :ip_addr => '192.168.50.10',
        :port1 => '8081',
        :port2 => '8080'
    }
}

Vagrant.configure("2") do |config|

    hosts.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.network "forwarded_port", guest: 80, host: boxconfig[:port1]
            box.vm.network "forwarded_port", guest: 9090, host: boxconfig[:port2]

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = "che-les13-" + "%s" % boxname
            end

            box.vm.provision "shell", path: "provision.sh"
        end
    end
end
