# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "web" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "web"
        subconfig.vm.network "private_network", ip: "192.168.50.51"
        subconfig.vm.network "forwarded_port", guest: 80, host: 8080

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les13-web"
            vb.cpus = 1
            vb.memory = "768"
        end

        subconfig.vm.provision "shell", path: "provision.sh"
    end

    config.vm.define "mntr" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "mntr"
        subconfig.vm.network "private_network", ip: "192.168.50.50"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les13-mntr"
            vb.cpus = 2
            vb.memory = "2048"
        end

        subconfig.vm.provision "shell", path: "provision.sh"
    end

end
