# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "monitoring" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "monitoring"
        subconfig.vm.network "forwarded_port", guest: 80, host: 8080
        subconfig.vm.network "forwarded_port", guest: 3306, host: 8081

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les13-monitoring"
            vb.cpus = 2
            vb.memory = "2048"
        end

#        subconfig.vm.provision "shell", path: "provision.sh"
        subconfig.vm.provision "shell", inline: <<-SHELL
            yum install -y epel-release
            yum install -y ansible

            cp -r /vagrant/ansible-monitoring/ /home/vagrant/
            chown -R vagrant:vagrant /home/vagrant/ansible-monitoring
        SHELL
    end

end
