# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    config.vm.define "les07" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "les07"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les07"
            vb.cpus = 1
            vb.memory = "768"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            yum install -y nano
            cp /vagrant/vg_rename.sh /home/vagrant && /home/vagrant/vg_rename.sh

            mkdir /usr/lib/dracut/modules.d/01test
            cp /vagrant/{module-setup,test}.sh /usr/lib/dracut/modules.d/01test
            dracut -f -v

            sed -i "s/rhgb/ /" /boot/grub2/grub.cfg
            sed -i "s/quiet/ /" /boot/grub2/grub.cfg

            echo "Reboot virtual machine ..."
            reboot
        SHELL

    end

end
