# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.define "centos7" do |srv|
        srv.vm.hostname = "centos7"

        config.vm.provider "virtualbox" do |srv|
            srv.name = "centos7"
            srv.cpus = 2
            srv.memory = "768"
        end

        srv.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            cp /vagrant/ps.sh /home/vagrant/
            yum install -y bc nano tmux
        SHELL

    end
end
