# -*- mode: ruby -*-
# vim: set ft=ruby :

MASK = "255.255.255.0"; 
VB_INTNET_NAME = "Dev-Infra_internal-net"

HOSTS = {

    :"gw" => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: "192.168.50.1", netmask: MASK, virtualbox__intnet: VB_INTNET_NAME},
        ],
        :port => [    
            {guest: 80, host: 8080},
            {guest: 443, host: 8081}
        ]
    },
    
    :"postgres" => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: "192.168.50.10", netmask: MASK, virtualbox__intnet: VB_INTNET_NAME},
        ],
        :port => []
    },

    :"web" => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: "192.168.50.20", netmask: MASK, virtualbox__intnet: VB_INTNET_NAME},
        ],
        :port => []
    }
}

Vagrant.configure("2") do |config|

    HOSTS.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end
            boxconfig[:port].each do |portconf|
                 box.vm.network "forwarded_port", portconf
            end

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = "che-les19-" + "%s" % boxname
            end

            box.vm.provision "shell", run: "always", inline: <<-SHELL
               
            SHELL

        end
    end
end
