# -*- mode: ruby -*-
# vim: set ft=ruby :

hosts = {
    :"client" => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "768",
        :ip_addr => '192.168.50.20'
    },
    :"server" => {
        :box_name => "centos/7",
        :cpu => '2',
        :ram => "2048",
        :ip_addr => '192.168.50.10',
        :http_port => '8080',
        :https_port => '8081'
    }
}

Vagrant.configure("2") do |config|

    hosts.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]

            case boxname.to_s
            when "server"
                box.vm.network "forwarded_port", guest: 80, host: boxconfig[:http_port]
                box.vm.network "forwarded_port", guest: 443, host: boxconfig[:https_port]
            end

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = "che-les19-" + "%s" % boxname
            end

            box.vm.provision "shell", path: "provision.sh"
        end
    end
end
