# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "srv.otus" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "srv.otus"
        subconfig.vm.network "private_network", ip: "192.168.1.10"
        subconfig.vm.network "forwarded_port", guest: 80, host: 8080

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les06-srv.otus"
            vb.cpus = 2
            vb.memory = "1024"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            cp /vagrant/srv.sh /home/vagrant && ./srv.sh
        SHELL
    end

    config.vm.define "ws.otus" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "ws.otus"
        subconfig.vm.network "private_network", ip: "192.168.1.20"
        subconfig.vm.network "forwarded_port", guest: 80, host: 8081

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les06-ws.otus"
            vb.cpus = 1
            vb.memory = "768"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            cp /vagrant/ws.sh /home/vagrant && ./ws.sh
        SHELL
    end

end
