# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "les06-server" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "les06-server"
        subconfig.vm.network "private_network", ip: "192.168.1.100"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "les06-server"
            vb.cpus = 2
            vb.memory = "1024"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            yum install -y htop nano
        SHELL
    end

    config.vm.define "les06-client" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "les06-client"
        subconfig.vm.network "private_network", ip: "192.168.1.200"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "les06-client"
            vb.cpus = 1
            vb.memory = "768"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            yum install -y htop nano
        SHELL
    end

end
