# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "master" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "master"
        subconfig.vm.network "private_network", ip: "192.168.1.100"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "les06-master"
            vb.cpus = 2
            vb.memory = "1024"
        end

# =>    subconfig.vm.provision "shell", path: "script.sh"
        subconfig.vm.provision "shell", inline: <<-SHELL
            echo -e "192.168.1.200\tslavet\tslave" >> /etc/hosts
            yum install -y epel-release
            yum install -y mc nano tree wget
            yum install -y redhat-lsb-core rpmdevtools rpm-build createrepo \
                yum-utils

            cp /vagrant/{master,slave}.sh /root/
        SHELL
    end

#    config.vm.define "slave" do |subconfig|
#        subconfig.vm.box = "centos/7"
#        subconfig.vm.hostname = "slave"
#        subconfig.vm.network "private_network", ip: "192.168.1.200"
#
#        subconfig.vm.provider "virtualbox" do |vb|
#            vb.name = "les06-slave"
#            vb.cpus = 1
#            vb.memory = "768"
#        end
#
#        subconfig.vm.provision "shell", inline: <<-SHELL
#            echo -e "192.168.1.100\tmaster\tmaster" >> /etc/hosts
#            yum install -y nano
#        SHELL
#    end

end
