# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "les10" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "les10"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "che-les10"
            vb.cpus = 1
            vb.memory = "768"
        end

        subconfig.vm.provision "shell", inline: <<-SHELL
            /vagrant/script.sh --provision
        SHELL

    end

end
