# -*- mode: ruby -*-
# vim: set ft=ruby :

hosts = {
    :"client" => {
        :box_name => "centos/7",
        :cpu => '1',
        :ram => "512",
        :ip_addr => '192.168.50.11'
    },
    :"server" => {
        :box_name => "centos/7",
        :cpu => '2',
        :ram => "1024",
        :ip_addr => '192.168.50.10'
    }
}

Vagrant.configure("2") do |config|

    hosts.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = "che-les14-" + "%s" % boxname
            end

            box.vm.provision "shell", path: "provision.sh"
        end
    end
end
